### ISSUE TITLE
Using !skip two times by the same user crashes bot

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#13]
I got my guys breaking this bot by spamming !skip,  but it's probably related to the previous issue.

Here's the dump I got.
```
kirk@kirk:~/git/mumbledj$ mumbledj -server=mumble.justsomegamers.com -port=6052 -username=Data -password="" -channel=M

Channel doesn't exist or one was not provided, staying in root channel...
Configuration successfully loaded!
panic: An error occurred while adding a skip to the current song.

goroutine 5 [running]:
main.skip(0xc20800ca00, 0xc2081051a0, 0xf, 0x0)
        /home/kirk/git/mumbledj/commands.go:224 +0xf0a
main.parseCommand(0xc20800ca00, 0xc2081051a0, 0xf, 0xc208104dd9, 0x4)
        /home/kirk/git/mumbledj/commands.go:45 +0x317
main.(*mumbledj).OnTextMessage(0xc28760, 0xc20810dea0)
        /home/kirk/git/mumbledj/main.go:69 +0xce
main.*mumbledj.OnTextMessage·fm(0xc20810dea0)
        /home/kirk/git/mumbledj/main.go:117 +0x31
github.com/layeh/gumble/gumbleutil.Listener.OnTextMessage(0xc20802aac0, 0xc20802aad0, 0xc20802aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kirk/go/src/github.com/layeh/gumble/gumbleutil/listener.go:44 +0x37
github.com/layeh/gumble/gumbleutil.(*Listener).OnTextMessage(0xc208030320, 0xc20810dea0)
        <autogenerated>:3 +0xaa
github.com/layeh/gumble/gumble.eventMultiplexer.OnTextMessage(0xc20803d410, 0xc20803d440, 0xc20810dea0)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/eventmultiplexer.go:62 +0x57
github.com/layeh/gumble/gumble.handleTextMessage(0xc20806e000, 0xc208033400, 0xb, 0x400, 0x0, 0x0)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/handlers.go:582 +0x917
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc20806e000)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:204 +0x613
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:108 +0x434

goroutine 1 [chan receive, 13 minutes]:
main.main()
        /home/kirk/git/mumbledj/main.go:128 +0x4ea

goroutine 17 [syscall, 13 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc20806e000)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:163 +0x2dc
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:109 +0x451

goroutine 13 [select]:
github.com/layeh/gumble/gumble_ffmpeg.(*Stream).sourceRoutine(0xc20802c680)
        /home/kirk/go/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:89 +0x452
created by github.com/layeh/gumble/gumble_ffmpeg.(*Stream).Play
        /home/kirk/go/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:47 +0x39d

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208011020, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011020, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010fc0, 0xc208106000, 0x1000, 0x1000, 0x0, 0x7fac5af31d70, 0xc208105030)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e088, 0xc208106000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fac5af33290, 0xc20802e088, 0xc2080be108, 0xc208106000, 0x1000, 0x1000, 0x740da0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801eca0, 0xc208106000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20800a780)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20800a780, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080be0b0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080be0b0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc
kirk@kirk:~/git/mumbledj$ ./data.sh
Channel doesn't exist or one was not provided, staying in root channel...
Configuration successfully loaded!
panic: An error occurred while adding a skip to the current song.

goroutine 5 [running]:
main.skip(0xc20800d700, 0xc2081025b0, 0xa, 0x0)
        /home/kirk/git/mumbledj/commands.go:224 +0xf0a
main.parseCommand(0xc20800d700, 0xc2081025b0, 0xa, 0xc2081038b1, 0x4)
        /home/kirk/git/mumbledj/commands.go:45 +0x317
main.(*mumbledj).OnTextMessage(0xc28760, 0xc2082bdce0)
        /home/kirk/git/mumbledj/main.go:69 +0xce
main.*mumbledj.OnTextMessage·fm(0xc2082bdce0)
        /home/kirk/git/mumbledj/main.go:117 +0x31
github.com/layeh/gumble/gumbleutil.Listener.OnTextMessage(0xc20802aac0, 0xc20802aad0, 0xc20802aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kirk/go/src/github.com/layeh/gumble/gumbleutil/listener.go:44 +0x37
github.com/layeh/gumble/gumbleutil.(*Listener).OnTextMessage(0xc208030320, 0xc2082bdce0)
        <autogenerated>:3 +0xaa
github.com/layeh/gumble/gumble.eventMultiplexer.OnTextMessage(0xc20803d410, 0xc20803d440, 0xc2082bdce0)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/eventmultiplexer.go:62 +0x57
github.com/layeh/gumble/gumble.handleTextMessage(0xc20806e000, 0xc208033400, 0xb, 0x400, 0x0, 0x0)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/handlers.go:582 +0x917
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc20806e000)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:204 +0x613
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:108 +0x434

goroutine 1 [chan receive]:
main.main()
        /home/kirk/git/mumbledj/main.go:128 +0x4ea

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc20806e000)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:163 +0x2dc
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:109 +0x451

goroutine 12 [select]:
github.com/layeh/gumble/gumble_ffmpeg.(*Stream).sourceRoutine(0xc20802c680)
        /home/kirk/go/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:89 +0x452
created by github.com/layeh/gumble/gumble_ffmpeg.(*Stream).Play
        /home/kirk/go/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:47 +0x39d

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208010f40, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010f40, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010ee0, 0xc208100000, 0x1000, 0x1000, 0x0, 0x7f6fe15e6d70, 0xc2080bd5a0)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e088, 0xc208100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f6fe15e8290, 0xc20802e088, 0xc2080be108, 0xc208100000, 0x1000, 0x1000, 0x740da0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801ec40, 0xc208100000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20800a960)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20800a960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080be0b0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080be0b0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by matthieugrieger** [comment]
Hi!

Thanks for the bug report. I think I just forgot to remove some panic statements from when I was testing the bot. This commit should hopefully fix it: https://github.com/matthieugrieger/mumbledj/commit/5d91ca95f4447e98080b04e2d21b8b4a7e3207f7. Let me know if it works!

**Comment by MrKrucible** [comment]
Sorry for the late response but I tested it out and it's fixed!

**Comment by MrKrucible** [comment]
Whoa, hold up one sec...
Some friends just double skipped while a song is playing, and that crashes the bot too. Tested it out and it's a related bug.

**Comment by matthieugrieger** [comment]
Are you sure you updated to the newest release? The dump doesn't really make sense with the code in its current state... According to the log the panic supposedly happens at `/home/kirk/gittest/mumbledj/commands.go:224`, which is located [here](https://github.com/matthieugrieger/mumbledj/blob/master/commands.go#L224).

Line 224 shouldn't be able to trigger any panics.

**Comment by MrKrucible** [comment]
Damn, wasn't paying attention and didn't see the 5d91ca9 commit! Got the new version up and all is well, so thanks for clarifying on that.

**Comment by matthieugrieger** [comment]
No problem! Glad it's working now.
