### ISSUE TITLE
Crash on !forceskip

### ISSUE THREAD

**Issue by chauffer** [matthieugrieger/mumbledj#154]
Steps to reproduce:

- Add a song
- !forceskip
- Crash 

#### Log output of bot with `--debug` flag 
```
INFO[0000] Checking for duplicate aliases...
INFO[0000] Performing startup checks...
INFO[0000] Checking for availability of services...      num_services=3
WARN[0000] A startup check discovered an issue. The service will be disabled.  error=No SoundCloud API key has been provided service=SoundCloud
INFO[0000] Checking YouTubeDL installation...
INFO[0000] Checking avconv installation...
INFO[0000] Checking aria2c installation...
INFO[0000] Attempting connection to server...            address=x port=x
INFO[0000] Setting default volume...                     volume=0.20
INFO[0000] Caching disabled.
INFO[0000] A user has disconnected or changed channels, updating skip trackers...  user=MumbleDJ
INFO[0005] Sending a message to channel...               channel=x message=<b>x</b> added <b>1</b> track to the queue:<br><i>x</i> from YouTube
INFO[0009] Sending a message to channel...               channel=x message=The current track has been forcibly skipped by <b>x</b>.
panic: runtime error: index out of range

goroutine 12 [running]:
panic(0xa06ee0, 0xc82000e080)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/matthieugrieger/mumbledj/bot.(*Queue).Skip(0xc82014ac00)
        /home/matthieu/go/src/github.com/matthieugrieger/mumbledj/bot/queue.go:204 +0x4c2
github.com/matthieugrieger/mumbledj/bot.(*Queue).PlayCurrent.func1(0xc82014ac00)
        /home/matthieu/go/src/github.com/matthieugrieger/mumbledj/bot/queue.go:313 +0x35
created by github.com/matthieugrieger/mumbledj/bot.(*Queue).PlayCurrent
        /home/matthieu/go/src/github.com/matthieugrieger/mumbledj/bot/queue.go:314 +0xb2e
```

**Comment by matthieugrieger** [comment]
Thanks for the bug report! I just pushed an update to fix it.
