### ISSUE TITLE
Go Panic 

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#180]
-  Bug report (encountered problems with MumbleDJ)

```
panic: runtime error: index out of range

goroutine 46 [running]:
panic(0x889d00, 0xc420010120)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/matthieugrieger/mumbledj/services.(*YouTube).getTrack(0xc42017c088, 0xc420134360, 0xb, 0xc42037e420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/matthieugrieger/mumbledj/services/youtube.go:212 +0x75c
github.com/matthieugrieger/mumbledj/services.(*YouTube).GetTracks(0xc42017c088, 0xc42043c053, 0x48, 0xc42037e420, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/matthieugrieger/mumbledj/services/youtube.go:164 +0x981
github.com/matthieugrieger/mumbledj/commands.(*AddCommand).Execute(0xd765d0, 0xc42037e420, 0xc42047ce30, 0x1, 0x1, 0x2, 0x2, 0xd765d0, 0x0, 0xc4200e7af0)
        /root/go/src/github.com/matthieugrieger/mumbledj/commands/add.go:63 +0x145
github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).executeCommand(0xc420190e60, 0xc42037e420, 0xc42043c051, 0x4a, 0xd42720, 0xd765d0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:317 +0xef
github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).FindAndExecuteCommand(0xc420190e60, 0xc42037e420, 0xc42043c051, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:276 +0x130
github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).OnTextMessage.func1(0xc420190e60, 0xc42019a0e0, 0xc42043c050, 0x4b)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:123 +0x90
created by github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).OnTextMessage
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:145 +0xfd
```
#### Description of your issue:
Append when I try to play : https://www.youtube.com/playlist?list=PLman5hRO0oXBg9uTT9PYrFZ2COPgoWhZv

**Comment by matthieugrieger** [comment]
Thanks for the bug report! This is happening because of the private video that is included with this particular playlist. It should be a pretty easy fix.

**Comment by matthieugrieger** [comment]
This panic shouldn't happen anymore. Let me know if you find any more!
