### ISSUE TITLE
Go Panic (second edition)

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#181]
Second Bug found : 

```
panic: runtime error: slice bounds out of range

goroutine 47 [running]:
panic(0x889d00, 0xc420010160)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/matthieugrieger/mumbledj/bot.(*Queue).PlayCurrent(0xc420168750, 0xd45520, 0xc4203e2000)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/queue.go:301 +0x8ab
github.com/matthieugrieger/mumbledj/bot.(*Queue).playIfNeeded(0xc420168750, 0xd765d0, 0x0)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/queue.go:356 +0xc6
github.com/matthieugrieger/mumbledj/bot.(*Queue).AppendTrack(0xc420168750, 0xd45520, 0xc4203e2000, 0x1, 0xc420404730)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/queue.go:76 +0x1cf
github.com/matthieugrieger/mumbledj/commands.(*AddCommand).Execute(0xd765d0, 0xc42008edc0, 0xc42047c3f0, 0x1, 0x1, 0x2, 0x2, 0xd765d0, 0xc4204995d8, 0xc42041c4e0)
        /root/go/src/github.com/matthieugrieger/mumbledj/commands/add.go:77 +0x32a
github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).executeCommand(0xc42016ce60, 0xc42008edc0, 0xc420468241, 0x2d, 0xd42720, 0xd765d0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:317 +0xef
github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).FindAndExecuteCommand(0xc42016ce60, 0xc42008edc0, 0xc420468241, 0x2d, 0x443e75, 0x300c420499658, 0x5c9e1a, 0x8e0700, 0xc4204997a
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:276 +0x130
github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).OnTextMessage.func1(0xc42016ce60, 0xc42015e5b0, 0xc420468240, 0x2e)
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:123 +0x90
created by github.com/matthieugrieger/mumbledj/bot.(*MumbleDJ).OnTextMessage
        /root/go/src/github.com/matthieugrieger/mumbledj/bot/mumbledj.go:145 +0xfd
panic: runtime error: slice bounds out of range
```
with the video https://www.youtube.com/watch?v=b1d7Llx4rm8 (one of my friend have weird taste I know)

**Comment by azlux** [comment]
Apparently, it happens with small videos. (same with this [one](https://www.youtube.com/watch?v=t9f73gMC5p4) )

**Comment by matthieugrieger** [comment]
Thanks again! I will take a look at these and fix them as soon as I can. I'm a bit busy with work-related things at the moment.

**Comment by azlux** [comment]
Forget about this issue, that's my fault when I was trying to remove ms from song duration string.

**Comment by matthieugrieger** [comment]
No worries!
