### ISSUE TITLE
Music doesn't start playing when I add a song.

### ISSUE THREAD

**Issue by AmalieNot** [matthieugrieger/mumbledj#30]
So I installed it (using Go 1.4.1), as well as installing ffmpeg and mercurial.  

However, when I add a song, the music doesn't start playing.  It seems to know the song is there, but is not playing it.
![image](https://cloud.githubusercontent.com/assets/8811239/5967972/8f813b22-a7e0-11e4-922f-9e433537a79c.png)

After reading other issues, I made sure gopus and goprotobuf were installed.  However, that does not seem to have fixed the issue.

I'm sure I'm doing something wrong, but do you know how to fix it?

**Comment by matthieugrieger** [comment]
Can you open up your Mumble client and navigate to Server -> Information and tell me what it says underneath the "Audio bandwidth" header?

**Comment by AmalieNot** [comment]
I've tried it in two servers with similar results.  The first server says this: 
![image](https://cloud.githubusercontent.com/assets/8811239/5968671/465122b6-a7e8-11e4-914c-e00f33d85249.png)

The second, which I'm hosting through linode, says this: 
![image](https://cloud.githubusercontent.com/assets/8811239/5968678/5c0388d8-a7e8-11e4-914c-c35298931bda.png)

**Comment by matthieugrieger** [comment]
Hmm.. strange. I was expecting that the server was on the CELT audio codec. It should be working if your server is on Opus.

You didn't mention `youtube-dl` in your original post, do you have that installed (and up to date)?

**Comment by AmalieNot** [comment]
I did install it before setting up the bot.  When I do "youtube-dl -U" it tells me it's up-to-date...

**Comment by matthieugrieger** [comment]
Another thing to maybe try... have you set `opusthreshold` in your `/etc/mumble-server.ini` or `/etc/murmur.ini` to 0? This forces Opus at all times, otherwise the server sometimes switches to CELT momentarily if a certain percentage of users don't support Opus.

**Comment by AmalieNot** [comment]
I do also have that set to 0.

**Comment by evanjohnman** [comment]
I'm also expiriencing issues. Similar server settings.

**Comment by matthieugrieger** [comment]
@AmalieNot, @evanjohnman:

I just tested out MumbleDJ on my own server and I am not experiencing the issue. Which distro are you two running?

**Comment by bontibon** [comment]
@matthieugrieger It may be worth doing some error checking [here](https://github.com/matthieugrieger/mumbledj/blob/4d082875307bd1e8bb96ed8555faab9cf1a5af94/song.go#L82) to see whether or not `ffmpeg` was successfully started.

**Comment by matthieugrieger** [comment]
@bontibon: Good point. I'll remember to add that in.

**Comment by AmalieNot** [comment]
If you meant distro of mumbledj, I'm fully updated.  I'm running ubuntu 14.10 on my server.

**Comment by matthieugrieger** [comment]
Oh, sorry, yeah I meant your Linux distro. I will have to look into this later as I am not quite sure what is causing problem. I'll post updates if I figure out anything.

**Comment by evanjohnman** [comment]
Ubuntu 14.04.1 64-bit.
Client

**Comment by matthieugrieger** [comment]
@bontibon: Could this possibly be related to this commit: https://github.com/layeh/gumble/commit/8f7277e3e110aa653534702e1871026208013533?

I have struggled with situations where `libav` and `ffmpeg` clash with each other before on Ubuntu.

**Comment by evanjohnman** [comment]
Dang. I figured that was the issue.

**Comment by matthieugrieger** [comment]
@evanjohnman: If possible, could you try removing `avconv` from your system? I believe it is a part of the package called `libav-tools`. If you can't remove it for some reason, no worry.

**Comment by evanjohnman** [comment]
Will do.

**Comment by evanjohnman** [comment]
Not showing up. Checking aptitude.

**Comment by matthieugrieger** [comment]
@AmalieNot, @evanjohnman: Are you two still having issues with getting the audio to play?

**Comment by evanjohnman** [comment]
I was unable to find that codec in aptitude. I'll look again now.

**Comment by evanjohnman** [comment]
Think I found it. (Didn't want Audacity on this anyway.

**Comment by matthieugrieger** [comment]
Let me know if you find out anything.

**Comment by evanjohnman** [comment]
I've removed libavtools, etc from my machine... 
Unfortunately, I had to SSH it from my phone and couldn't test it. I tried connecting it to a private server (with opus forced, running off RPi :P) but I wasn't able to get it to respond to my mumble app. 

This is likely a bug with my iPhone, but it (mumdj) ran without error from SSH. I hope this is just a glitch with the app. 
I'll report any further bugs to you, should I encounter any more.

**Comment by evanjohnman** [comment]
The issue was not fixed, although I need to try rebooting my PC.

**Comment by evanjohnman** [comment]
Tried reboot; no change.

Posting 'make install' script output:

mkdir -p ~/.mumbledj/config
mkdir -p ~/.mumbledj/songs
if [ -a ~/.mumbledj/config/mumbledj.gcfg ]; then mv ~/.mumbledj/config/mumbledj.gcfg ~/.mumbledj/config/mumbledj_backup.gcfg; fi;
/bin/sh: 1: [: -a: unexpected operator
cp -u mumbledj.gcfg ~/.mumbledj/config/mumbledj.gcfg
sudo cp -f mumbledj /usr/local/bin/mumbledj

There seems to be a messed up operator. Maybe it's related to that.

**Comment by AmalieNot** [comment]
I have the same make output.  I'll look for libavtools now - sorry, some things came up that took me afk for a bit.

**Comment by evanjohnman** [comment]
Question: what is the minimum version of opus required to run this? Because my install defaulted to the 1.0 release, and 1.2 is available.

**Comment by AmalieNot** [comment]
I don't appear to have avconv or libav-tools installed.  I'm wondering about the opus version thing myself.

**Comment by matthieugrieger** [comment]
@evanjohnman: I'm not sure what is going on with your `make install` output. Running `make install` on my Ubuntu installation doesn't cause any errors.

Also, via `dpkg -s libopus0` I am running version 1.1 of `opus`.

**Comment by evanjohnman** [comment]
Hmm... I need to test with the updated version of opus. (My old one
returned 1.0, this says 1.1. Hope that clears it up.

On Saturday, January 31, 2015, Matthieu Grieger <notifications@github.com>
wrote:

> @evanjohnman <https://github.com/evanjohnman>: I'm not sure what is going
> on with your make install output. Running make install on my Ubuntu
> installation doesn't cause any errors.
>
> Also, via dpkg -s libopus0 I am running version 1.1 of opus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthieugrieger/mumbledj/issues/30#issuecomment-72348599>
> .
>


-- 
Evan

**Comment by matthieugrieger** [comment]
@evanjohnman: Let me know what happens. I just fully updated my server, updated/recompiled MumbleDJ, rebooted my server (which has MumbleDJ and my Mumble server), and it still works fine.

**Comment by evanjohnman** [comment]
Audio has not worked yet. It download the files and then doesn't play the
music


-- 
Evan

**Comment by evanjohnman** [comment]
@matthieugrieger All I can say is, it's the part that @bontibon Pointed out that is causing the issue. `Opus`, `Mercurial`, and `ffmpeg` are all installed correctly.

**Comment by matthieugrieger** [comment]
@evanjohnman: Can you update to the newest release and give me the output when you try to play a song? Hopefully this will help us find the issue.

**Comment by evanjohnman** [comment]
Will do!

**Comment by evanjohnman** [comment]
Words cannot express how irritated I am at this right now.
panic, it did not. 
;-;

**Comment by matthieugrieger** [comment]
Huh. So it didn't panic, but it also didn't play audio?

**Comment by evanjohnman** [comment]
Yes. And now with the latest release I can't build.

I apologize for being a problem child.

./commands.go:273: cannot call non-function dj.audioStream.Volume (type float32)
./commands.go:278: dj.audioStream.SetVolume undefined (type *gumble_ffmpeg.Stream has no field or method SetVolume)
./commands.go:279: cannot call non-function dj.audioStream.Volume (type float32)
./main.go:54: dj.audioStream.Done undefined (type *gumble_ffmpeg.Stream has no field or method Done)
./main.go:55: dj.audioStream.SetVolume undefined (type *gumble_ffmpeg.Stream has no field or method SetVolume)

**Comment by matthieugrieger** [comment]
That build error signifies to me that something on your end isn't installed correctly. I receive no build errors, and I test if each release builds before I release it.

Are you sure that you have `gumble_ffmpeg` installed correctly? I would check the `src` folder in your Go root to make sure that `gumble_ffmpeg` is there and isn't corrupted or anything.

**Comment by bontibon** [comment]
@matthieugrieger I have been updating `gumble_ffmpeg` today. It may be worth looking into a dependency manager for mumbledj. That would prevent breaking your program from breaking when other people (in this case, me) make API changes on their projects.

**Comment by matthieugrieger** [comment]
@bontibon: Thanks for the suggestion. I'm still getting the hang of Go, so
I don't know all the best practices yet. :)

I'll add something like `goop` later.

**Comment by AmalieNot** [comment]
Okay, I went to update this today via the "make clean, make, make install" directions you provided and get this output from "make":

go get -u github.com/layeh/gumble/gumble
go get -u github.com/layeh/gumble/gumbleutil
go get -u github.com/layeh/gumble/gumble_ffmpeg
go get -u code.google.com/p/gcfg
go get -u github.com/kennygrant/sanitize
go get -u github.com/jmoiron/jsonq
go build .
# _/home/strongsuit/mumbledj
./commands.go:273: cannot call non-function dj.audioStream.Volume (type float32)
./commands.go:278: dj.audioStream.SetVolume undefined (type *gumble_ffmpeg.Strea                                  m has no field or method SetVolume)
./commands.go:279: cannot call non-function dj.audioStream.Volume (type float32)
./main.go:54: dj.audioStream.Done undefined (type *gumble_ffmpeg.Stream has no f                                  ield or method Done)
./main.go:55: dj.audioStream.SetVolume undefined (type *gumble_ffmpeg.Stream has                                   no field or method SetVolume)
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Error 2

**Comment by matthieugrieger** [comment]
@AmalieNot: That's a bug with the make process at the moment.

I will be adding a dependency manager later to help counteract this. I
would do it now but I am in class. :)

**Comment by AmalieNot** [comment]
Thank you!

**Comment by hamilton5** [comment]
!add https://www.youtube.com/playlist?list=PLFgquLnL59alW3xmYiWRaoz0oM3H17Lth

would not start playing or even acknowledge it was added... I added another song after and nothing happened... I did a !reset and then got a crash (panic:runtime error: index out of range) .

**Comment by matthieugrieger** [comment]
@AmalieNot, @evanjohnman, @hamilton5: The build issues have been fixed in the latest release. Sorry about that!

I will be adding a dependency manager to prevent problems like this from happening in the future.

**Comment by hamilton5** [comment]
I have successfully built the new version... the issue with invalid playlist url still stands.

**Comment by AmalieNot** [comment]
Well, that was exciting.

So, when I add a song now, this is what happens:

root@munin:/home/strongsuit/mumbledj# screen -S mumblebot
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc20806c000)
        /root/go/src/github.com/layeh/gumble/gumble/client.go:166 +0x2dc
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /root/go/src/github.com/layeh/gumble/gumble/client.go:112 +0x485

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208010df0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010df0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010d90, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7fbcb6bd4d70, 0xc20812cb30)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e080, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fbcb6bd6400, 0xc20802e080, 0xc208060ec8, 0xc20800f000, 0x1000, 0x1000, 0x748e60, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801e9e0, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20800a6c0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20800a6c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208060e70)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc208060e70)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

In mumble, this is what happened:
![image](https://cloud.githubusercontent.com/assets/8811239/6013113/24798ea6-ab1e-11e4-94ba-e16fbe62d297.png)

**Comment by hamilton5** [comment]
@AmalieNot it concerns me you run things like this as root.

**Comment by AmalieNot** [comment]
It's a clean server install I have no issue wiping.  I was having some other minor issues with my other server install.

**Comment by matthieugrieger** [comment]
@hamilton5: That first playlist URL you gave works fine for me. The second one, however, did produce a crash and that should be fixed now.

@evanjohnman, @AmalieNot: Try building MumbleDJ with the latest release. The way that dependencies are handled and built is different now, so it *might* fix your problems (fingers crossed). Just make sure to install `openal` beforehand (I believe it should be `sudo apt-get install libopenal-dev` on Ubuntu) or else the compile will not work.

@bontibon: I added `goop` to handle dependency management. Thanks again for the suggestion, I like this much better.

**Comment by AmalieNot** [comment]
I get nearly identical vomit with this latest build

bufio.(*Reader).Peek(0xc20800a6c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080be0b0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080be0b0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

**Comment by hamilton5** [comment]
uh... my make retured this:

go get github.com/nitrous-io/goop
goop update
make: goop: Command not found
make: *** [mumbledj] Error 127

**Comment by matthieugrieger** [comment]
@hamilton5: You don't have your `$PATH` variable set correctly. You need to append `$GOPATH` to it. And yes, you need OpenAL because the dependency manager downloads it and compiles it. It may be used in the future so it would be good to have it anyway.

@AmalieNot: Are you copying your build outputs from `screen`? I think some of your logs are getting cut off because of that, so it's kinda hard to find the issue.

**Comment by evanjohnman** [comment]
I'm sorry I haven't been on for a while. Projects for class, etc.
I'll not be back for a while, unfortunately. THough I may be able to work on it over the weekend.

**Comment by matthieugrieger** [comment]
@evanjohnman No worries! I'm at a busy time at school as well.

**Comment by jakexks** [comment]
If you're having trouble building mumbledj I built and packaged it into a docker container. You can run my build by [installing docker](https://docs.docker.com/installation/) then running:
``` docker run --rm -it jakexks/mumbledj -cert="/crt.crt" -key="/key.key" -server=[your server] -port=64738 -username=MumbleDJ -password="" -channel=root ```

**Comment by matthieugrieger** [comment]
@AmalieNot, @evanjohnman: Do you two still experience issues? No worries if you haven't gotten the chance to try it out once more. I'm just curious.

**Comment by matthieugrieger** [comment]
Closing due to inactivity. If there are still issues, please feel free to let me know!

**Comment by AmalieNot** [comment]
Hey -

The docker solution is working, but I'm still having issues if I try to run it otherwise.

Sorry for the inactivity.  I've been trying to stay afloat with grading for my class, since they have midterms soon.  My university has spring break next week, though, so I'll probably try it out again then.

**Comment by matthieugrieger** [comment]
@AmalieNot: Cool, glad it is working one way or another. :)

No need to worry about response times!

**Comment by ogkinetic1** [comment]
Can anyone please help me? I'm trying to install MumbleDJ and after I type makeinstall i get this error...
$ make install
mkdir -p ~/.mumbledj/config
mkdir -p ~/.mumbledj/songs
if [ -a ~/.mumbledj/config/mumbledj.gcfg ]; then mv ~/.mumbledj/config/mumbledj.gcfg ~/.mumbledj/config/mumbledj_backup.gcfg; fi;
/bin/sh: 1: [: -a: unexpected operator
cp -u config.gcfg ~/.mumbledj/config/mumbledj.gcfg
if [ -d ~/bin ]; then cp -f mumbledj* ~/bin/mumbledj; else sudo cp -f mumbledj* /usr/local/bin/mumbledj; fi;
cp: cannot stat ‘mumbledj*’: No such file or directory
make: *** [install] Error 1

**Comment by hamilton5** [comment]
ogkinetic1 why would you put that in this 'Music doesn't start playing when I add a song.'?

You had no problems building mumbledj the bin is in the folder? what shell are you using?
