### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mkody** [matthieugrieger/mumbledj#45]
![Heh](http://s.kdy.ch/1yawi.png)
(He doesn't respond because of permissions on this channel, but that doesn't affect)

After **exactly** 5 minutes, the bot crashes.
```
Configuration successfully loaded!
panic: runtime error: index out of range

goroutine 8 [running]:
main.(*SongCache).ClearExpired(0xc20802a990)
        /root/mumbledj/cache.go:76 +0x5cd
created by main.(*mumbledj).OnConnect
        /root/mumbledj/main.go:69 +0x53c

goroutine 1 [chan receive, 5 minutes]:
main.main()
        /root/mumbledj/main.go:182 +0x988

goroutine 17 [syscall, 5 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [IO wait]:
net.(*pollDesc).Wait(0xc20807a060, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20807a060, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20807a000, 0xc2080ca000, 0x8000, 0x8000, 0x0, 0x7ff952e2cbf0, 0xc208154158)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e020, 0xc2080ca000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20806a1b0, 0x7ff952e2e7c8, 0xc20802e020, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208078000, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208078000, 0xc208154150, 0x2, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x166
io.ReadAtLeast(0x7ff952e2eef0, 0xc208078000, 0xc208154150, 0x2, 0x8, 0x2, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff952e2eef0, 0xc208078000, 0xc208154150, 0x2, 0x8, 0x4, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x6d
encoding/binary.Read(0x7ff952e2eef0, 0xc208078000, 0x7ff952e2ee68, 0xbe4698, 0x6c6da0, 0xc208154148,
 0x0, 0x0)
        /usr/local/go/src/encoding/binary/binary.go:148 +0x12d
github.com/layeh/gumble/gumble.(*Conn).ReadPacket(0xc2080601c0, 0xc20812e000, 0x0, 0x0, 0x0, 0x0, 0x
0)
        /root/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/conn.go:46 +0x22a
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc20809a000)
        /root/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:173 +0x8d
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /root/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:113 +0x515

goroutine 6 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc20809a000)
        /root/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:156 +0x2dc
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /root/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:114 +0x532
```

**Comment by matthieugrieger** [comment]
Thanks for the report! I believe that somebody else pointed this out in a comment on a commit I recently made.

The reason why it is exactly 5 minutes is because there is now a background thread that checks for expired songs every 5 minutes. I'm assuming you have enabled the caching feature?

Off-topic: What theme are you using for Mumble? It looks really nice.

**Comment by mkody** [comment]
Yes, I've enabled the caching. Thanks for the quick response!

I'm using [xPoke/MetroMumble](https://github.com/xPoke/MetroMumble/releases/)

**Comment by matthieugrieger** [comment]
Should be fixed now!

**Comment by mkody** [comment]
Yup, it's working now :+1: 
Thanks!

**Comment by matthieugrieger** [comment]
Great!
