### ISSUE TITLE
MumbleDJ does not have a valid YouTube API key.

### ISSUE THREAD

**Issue by satinez** [matthieugrieger/mumbledj#84]
Hello guys (:

Im getting the Info from the Bot in the mumble chat. Bot is working great.
I have registred 2 APIs, 1 very fresh tonight but still I get this warning :(

Im using Ubuntu 15.04

What im doing wrong?

greet;s satinez

**Comment by matthieugrieger** [comment]
Hi!

Did you export your new API key in `~/.bashrc`?

**Comment by satinez** [comment]
Hello :) Sure I did :(

**Comment by matthieugrieger** [comment]
Hmm. Might be an environment issue then.

Do you happen to be running/starting the not via a `cron` job, an `upstart` service, or something similar?

**Comment by satinez** [comment]
No, just started directly from console.

**Comment by matthieugrieger** [comment]
I don't think it has to do with Golang.

Please read through the following piece of README and let me know if you're sure you followed each step exactly: https://github.com/matthieugrieger/mumbledj#youtube-api-keys

**Comment by satinez** [comment]
Good Morning :dancer: 

Yes i followed the tutorial and created the key successfully. No error in console, only just the info text in chat.

**Comment by matthieugrieger** [comment]
Hmm, strange. To be honest I'm not quite sure what the issue is here.

You will receive that chat message when the YouTube API responds with a 403 error. A 403 error corresponds with not having permission to view whatever you are requesting.

Are you running the bot through a server provider or just on your own machine? In the past there has been issues with specific hosting providers.

**Comment by satinez** [comment]
Well I tested this with my Linux machine at home also. The real server its a dedicated Server, Hosted by Hetzner.de, no managed server, i have full control, so it must be something :(

Bot works fine, fast and so, but dont accept add command :(

greet;s satinez

**Comment by satinez** [comment]
Ok 
1. Clean Server install Debian 8.1 64bit
2. Added a new google account, created a new clean Youttube API key.
3. Followed the MumbleDJ tutorial

BOT connects fine, no errors, no fails. But im getting the same error.

greet;s satinez

**Comment by MichaelOultram** [comment]
I'm guessing the issue is with youtube-dl, but the bot doesn't print out a useful message. Maybe try downloading a sample song via youtube-dl (I just picked the top song for the UK) `youtube-dl --verbose --no-mtime --output ~/.mumbledj/songs/vjW8wmF5VWc.m4a --format m4a vjW8wmF5VWc` and see what error it produces (if any)?

**Comment by satinez** [comment]
Hmmmmmmmmmmm :(

youtube-dl --verbose --no-mtime --output ~                                              /.mumbledj/songs/vjW8wmF5VWc.m4a --format m4a vjW8wmF5VWc
[debug] System config: []
[debug] User config: [u'--force-ipv4', u'--extract-audio', u'--no-mtime']
[debug] Command-line args: [u'--verbose', u'--no-mtime', u'--output', u'/root/.m                                              umbledj/songs/vjW8wmF5VWc.m4a', u'--format', u'm4a', u'vjW8wmF5VWc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.9 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-                                              vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.0                                              4.1
[debug] Proxy map: {}
[youtube] vjW8wmF5VWc: Downloading webpage
[youtube] vjW8wmF5VWc: Downloading video info webpage
ERROR: vjW8wmF5VWc: YouTube said: Unfortunately, this video is not available in                                               your country because it could contain music, for which we could not agree on con                                              ditions of use with GEMA.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract                                              _info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in                                               extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1078, i                                              n _real_extract
    expected=True, video_id=video_id)
ExtractorError: vjW8wmF5VWc: YouTube said: Unfortunately, this video is not avai                                              lable in your country because it could contain music, for which we could not agr                                              ee on conditions of use with GEMA.

**Comment by matthieugrieger** [comment]
Ah.. This would explain it. Based on the domain name of your server provider, do you live in Germany?

**Comment by MichaelOultram** [comment]
Silly me, I didn't think about regions. Maybe try replacing the video id
with one that works in your/the servers country?

**Comment by satinez** [comment]
Thanks. I dont understand. The server is in germany, yes.
If i take another youtube file, it works very well on console.
Some not working, thats ok cuz of region.

But the MumbleDJ Bot say me to every YT link : MumbleDJ does not have a valid YouTube API key. :(

**Comment by MichaelOultram** [comment]
Ah okay. If youtube-dl can download a video, then it must be the bot.

Just a last check before I have now clue what it is. Can you make sure that `echo $YOUTUBE_API_KEY` prints out the API key? And make sure that you are not running the bot with sudo.

**Comment by satinez** [comment]
Yes the YoutubeKey shows fine, stored fine in the .bashrc.

I installed the server about 10 times :(

**Comment by MichaelOultram** [comment]
Can you try navigating to this page to check whether youtube is happy with your API key: `https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=OglS3Q0Zxik&key=<YOUTUBE_API_KEY>`, replacing `<YOUTUBE_API_KEY>` with your API key.

**Comment by satinez** [comment]
I also tried with another key and another gmail account :(

{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "keyExpired",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}

**Comment by MichaelOultram** [comment]
Well I guess we worked out what the issue is, but I'm not sure how to solve it. Maybe you should wait 5 to 10 minutes between creating the key and using it? Google is seemingly slow to update to API key changes.

**Comment by satinez** [comment]
Yes I have tried that :(
Same error :(

Can someone provide a dependency list for the whole application? Maybe something is missing.

**Comment by MichaelOultram** [comment]
Whatever key you used to produce the second output starting with the following is a valid key (and should work in the bot)
```
{
"kind": "youtube#videoListResponse",
"etag": "\"sGDdEsjSJ_SnACpEvVQ6MtTzkrI/41bmv8-lVLCK5FrwbR5itaT2Ss4\"",
"pageInfo": {
"totalResults": 1,
"resultsPerPage": 1
},
```

If not however, the full dependency (or at least what I had to install to make the bot work):
* golang >1.4
 - you can check with `go version`
 - bot won't compile without it, so I'm pretty sure you've got this.
* opus
 - bot won't compile without it, so I'm pretty sure you've got this.
* ffmpeg >2.0 (or youtube-dl won't be able to download a video)
  - you can check this with `ffmpeg -version`
  - using `apt-get install ffmpeg` will give you an outdated version of ffmpeg, get it from the website instead.
  - @matthieugrieger maybe you should make this clear in the readme?
* youtube-dl
 - check for latest update with `youtube-dl -U`

**Comment by matthieugrieger** [comment]
Thanks for all the help @MichaelOultran.

Yes, the dependencies need to be a bit more clear in the README. I am currently working on a rewrite and will hopefully have an easier installation process set up, but I will update the README in the meantime.

The error messaging is one of the bigger problems with the current code. They aren't very descriptive, and sometimes just plain wrong.

**Comment by RCambier** [comment]
I don't know if it's related, but I had the same problem and I solved it by using a **browser** api key instead of a **server** api key. It now works !

**Comment by matthieugrieger** [comment]
Closing due to inactivity. @satinez, let me know if you are still having issues and I will reopen.

**Comment by amosonlinellp** [comment]
oimaa coupon code in oimaa.net
