### ISSUE TITLE
The audio download for this video failed [YOUTUBE ONLY]

### ISSUE THREAD

**Issue by Ariios** [matthieugrieger/mumbledj#95]
Whenever a user tries to add a youtube link to the bot using the !add command, it usually fails.  This only occurs with youtube links as soundcloud links work almost all the time from what I can tell.  I've reinstalled youtube-dl, updated it, and re-did my API access keys multiple times now and most videos still generally fail to download.  I have also tried the IPV4 trick and that did not work either.  I'm at a loss here lol.

**Comment by matthieugrieger** [comment]
Strange... I'm not sure what could be causing the issue if you updated `youtube-dl` and everything.

When you say you redid your API access keys, did you make sure to place the IP of your server in the API key settings?

**Comment by Ariios** [comment]
After reading your reply I added the IP of my server to the API key settings, but I'm still running into the same problem.

**Comment by matthieugrieger** [comment]
Can you show me what happens when you execute this command?

`youtube-dl --verbose --no-mtime --output ~/.mumbledj/songs/test.m4a --format m4a --prefer-ffmpeg <youtube_url_here>`

Replace `<youtube_url_here>` with the URL you are trying to add.

**Comment by Ariios** [comment]
youtube-dl --verbose --no-mtime --output ~/.mumbledj/songs/test.m4a --format m4a --prefer-ffmpeg https://www.youtube.com/watch?v=QuFb2iRhM7M
[debug] System config: [u'--extract-audio']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-mtime', u'--output', u'/home/pi/.mumbledj/songs/test.m4a', u'--format', u'm4a', u'--prefer-ffmpeg', u'https://www.youtube.com/watch?v=QuFb2iRhM7M']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.3 - Linux-3.18.11-v7+-armv7l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] QuFb2iRhM7M: Downloading webpage
[youtube] QuFb2iRhM7M: Downloading video info webpage
[youtube] QuFb2iRhM7M: Extracting video information
[youtube] {22} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] QuFb2iRhM7M: Downloading player https://s.ytimg.com/yts/jsbin/html5player-new-en_US-vflQZZsER/html5player-new.js
[youtube] {43} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {18} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {5} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {36} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {17} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {137} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {248} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {264} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {136} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {247} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {135} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {244} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {134} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {243} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {133} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {242} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {160} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {140} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] {171} signature length 41.43, html5 player new-en_US-vflQZZsER
[youtube] QuFb2iRhM7M: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-a0hvn-jive.googlevideo.com/videoplayback?id=42e15bda246133b3&itag=141&source=youtube&requiressl=yes&mm=31&mv=m&ms=au&mn=sn-a0hvn-jive&pl=19&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6704137&lmt=1417258080731632&dur=210.256&sver=3&signature=32B6CFD449E51FB95DF7E82D222C322ACD1FE0BD.8BB2C3AA79B4FE490A8AA5020D75B8520B374B29&mt=1446100716&fexp=9405997,9408710,9414764,9415436,9416126,9416837,9417707,9418199,9419966,9420655,9421551,9422527,9422541,9422596,9423317,9423428,9423519&key=dg_yt0&upn=BYWNsYEXVks&ip=24.219.192.106&ipbits=0&expire=1446122427&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,ms,mn,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: /home/pi/.mumbledj/songs/test.m4a
[download] 100% of 6.39MiB in 00:01
[ffmpeg] Correcting container in "/home/pi/.mumbledj/songs/test.m4a"
WARNING: Your copy of ffmpeg is outdated, update ffmpeg to version 1.0 or newer if you encounter any errors.
[debug] ffmpeg command line: ffmpeg -y -i file:/home/pi/.mumbledj/songs/test.m4a -c copy -f mp4 file:/home/pi/.mumbledj/songs/test.temp.m4a
ERROR: Failed to set value 'copy' for option 'c'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1712, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 457, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 158, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 154, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by Ariios** [comment]
I guess I would need to update ffmpeg, however I'm honestly not too familiar with how to do so on a Debian system so some pointers would be nice lol.

**Comment by MichaelOultram** [comment]
The ffmpeg that apt-get installs is outdated. The easiest way to install ffmpeg is first removing the old version `sudo apt-get remove ffmpeg`. Then download the compressed binary to tmp `wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O /tmp/ffmpeg.tar.xz`. Extract the contents `tar -xvf /tmp/ffmpeg.tar.xz --strip 1 --no-anchored ffmpeg ffprobe`. Make the binary executable `chmod a+rx ffmpeg ffprobe` and then move the files to a folder in the path directory `sudo mv ff* /usr/bin`.

**Comment by matthieugrieger** [comment]
@Ariios: Did updating `ffmpeg` fix your issue?

**Comment by hamilton5** [comment]
it should have... debian is going threw this change now. I had the same issue and needed to upgrade ffmpeg to testing version. still solid thanks you guys for the work.

**Comment by Ariios** [comment]
Lol sorry for having not responded for a few days.  I think I managed to mess up my reinstallation of ffmpeg and haven't had the time to fix it yet, but once I do I'll let you know if it fixed the issue.

**Comment by matthieugrieger** [comment]
Closing due to inactivity. @Ariios, let me know if you are still having issues and I will reopen.
